language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

# install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install coverage coveralls

#before_script:
#  - mkdir data

# run tests, e.g. python setup.py test
script:
  - coverage run --source="partialhash" setup.py test

# run coverage
after_success:
  - coveralls

# post to slack
notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
